# Write a function to reverse a string in Python
 

In [1]:
def reverse_string(string):
    return string[::-1]
print(reverse_string("hello"))

olleh


# Q.2 Check if a string is a palindrome.


In [2]:
def is_palindrome(s):
    return s == s[::-1]
print(is_palindrome("madam"))

True


# Q 3. Write a function to find the nth Fibonacci number using recursion.


In [4]:
def fib(n):
    if n <= 1:
        return n
    else:
        return fib(n-1) + fib(n-2)
    
fib(10)

55

# Q.4 Find indices of two numbers that add up to a specific target in an array.


In [5]:
def sum_of_two(nums, target):
    for i in range(len(nums)-1):
        if nums[i] + nums[i+1] == target:
            return i, i+1


print(sum_of_two([2, 7, 3, 15], 10))

(1, 2)


# Q.5 Write a Python function to calculate the factorial of a number.


In [6]:
def factorial(n):
    if n == 0 or n==1:
        return n 
    else:
        return n*factorial(n-1)
    
print(factorial(5))

120


# Q.6 How would you count the occurrences of each element in a list?


In [11]:

from collections import Counter
def count_occurences(nums):
    return Counter(nums)

print(count_occurences([1, 2, 2, 3, 3, 3]))

Counter({3: 3, 2: 2, 1: 1})


# Q.7 How would you load a CSV file into a Pandas DataFrame?


In [13]:
import pandas as pd 
#df = pd.read_csv('file.csv')

# Q.8 Write a function to calculate the element-wise sum of two Numpy arrays.


In [5]:
import numpy as np 
arr1 = np.array([1,2])
arr2 = np.array([2,3])
result = np.add(arr1, arr2)
result

array([3, 5])

# Q.9 How would you extract the diagonal elements of a Numpy matrix?


In [7]:
import numpy as np 
matrix = np.array([[1,2,3], [4,5,6]])
print(np.diagonal(matrix))

[1 5]


# Q.10 Write code to reshape a 1D Numpy array into a 2D array with 3 rows.


In [11]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,6])
arr2 = arr1.reshape(3,2)
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

# Q.11 Write a Python function to calculate the mean, median, and standard deviation of a list of numbers.


In [12]:
lst = [10, 20, 30, 40]
import numpy as np 
mean = np.mean(lst)
median = np.median(lst)
st_dev = np.std(lst)
print(mean, median, st_dev)

25.0 25.0 11.180339887498949


# Q 12. How would you handle missing values in a DataFrame?


In [14]:
#df.fillna(df.mean(),inplace = true)

In [ ]:
#df.dropna(inplace=true)

# Q 13. How do you read and write data from a file in Python?


In [ ]:
with open('file.txt', 'r') as file:
    content = file.read()
print(content)

In [ ]:
with open('file.text','w') as file:
    file.write("hello world")

# Q 14. Write an SQL query to retrieve all columns from a table named employees where the age is greater than 30.


In [15]:
selecy * from employees
where age > 30;

SyntaxError: invalid syntax (4043437492.py, line 1)

# Q 15. Write an SQL query to join two tables: orders and customers, where the customer_id in orders matches the id in customers.


In [ ]:
select orders.order_id, customers.customer_name
from customers 
join order on customers.customer_id = orders.customerID

# Q 16. Write an SQL query to find the average salary for each department in a company table, but only for departments with more than 10 employees.


In [ ]:
select dept, avg(salary)
from employees
group by dept
having count(employee_id)>10

# Q 17. Write an SQL query to find all employees whose salary is greater than the average salary in the employees table.


In [ ]:
select * from employees
where salary > (select avg(salary) from employee)

# Q 18. Write an SQL query to find the total sales from the sales table for each product.


In [ ]:
select product_id, sum(sales_amount)
from sales
group by product_id

# Q 23. Explain how a hash table works. Provide an example.


In [16]:
# Hash table is a data structure that stores key-value pairs. 
# It uses a hash function to compute an index into an array of buckets or slots, from which the desired value can be found.
hash_table = {}
hash_table["name"]= "rihan"
hash_table["age"] = 22
hash_table["city"] = "america"

print(hash_table["name"])
print(hash_table["age"])
print(hash_table["city"])

rihan
22
america


# Q 24. Find the First Non-Repeated Character in a String


In [28]:
def first_non_repeated_char(string):
    char_count = {}
    for char in string:
        if char in char_count:
            char_count[char] += 1
        else:
            char_count[char] = 1
    for char in string:
        if char_count[char] == 1:
            return char
    return None
string = 'swiss'        
print(first_non_repeated_char(string)) 
print(first_non_repeated_char("aabbcc"))

w
None


# Q 25. Check if Two Strings are Anagrams of Each Other.




In [33]:
def are_anagrams(str1, str2):
    if len(str1) != len(str2):
        return false
    else:
        return sorted(str1) == sorted(str2)
print(are_anagrams("listen", "silent"))  
print(are_anagrams("hello", "world"))

True
False


# Q 26. How do you transpose a NumPy array?


In [35]:
import numpy as np
arr1 = np.array([[1,2],[4,5]])
arr1.T


array([[1, 4],
       [2, 5]])

# Q 27 Find the median of two sorted arrays of different sizes.


In [37]:
def find_median(arr1,arr2):
    merged=  sorted (arr1 + arr2)
    n = len(merged)
    return (merged[n//2] + merged[n//2 -1])/2 if n%2 ==0 else merged[n//2]

print(find_median([1, 3], [2, 4, 5]))

3


# Q 29. Find the kth smallest element in an unsorted array.


In [38]:
import heapq
def kth_smallest(arr, k):
    return heapq.nsmallest(k,arr)[-1]
    
print(kth_smallest([7, 10, 4, 3, 20, 15], 3))

7


# Q 30. Generate all possible permutations of a given list of numbers.


In [42]:
from itertools import permutations
def generate_permutations(arr):
    return list(permutations(arr))

print(generate_permutations([1, 2, 3]))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


# Q 37. Perform one-hot encoding of categorical variables in a dataset.


In [44]:
import pandas as pd

def one_hot_encode(data, column):
    return pd.get_dummies(data, columns = [column])

df = pd.DataFrame({'Color': ['Red', 'Blue', 'Green']})
print(one_hot_encode(df, 'Color'))

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
